# Generated by Django 5.2.7 on 2025-11-30 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaMatch', models.DateTimeField(auto_now_add=True)),
                ('estadoMatch', models.CharField(default='activo', max_length=50)),
                ('usuarioA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_usuario_a', to=settings.AUTH_USER_MODEL)),
                ('usuarioB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_usuario_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
